Repository apache/maven-dependency-plugin, pull requests merged in 2025-07, with the labels that each got.

#537 Fix - markersDirectory is not working when unpack goal is executed from command line
  src/main/java/org/apache/maven/plugins/dependency/fromConfiguration/UnpackMojo.java
Labels: bug

#1496 Cleanups dependencies
  pom.xml
Labels: maintenance

#1497 Add Apache 2.0 LICENSE file
  LICENSE
Labels: skip-changelog
