Repository apache/maven-dependency-plugin, pull requests merged in 2025-08, with the labels that each got.

#1502 Build by Maven 4
  .github/workflows/maven-verify.yml
  src/it/projects/list-repositories/verify.groovy
  src/it/projects/tree-excluded/expected-v4.txt
  src/it/projects/tree-excluded/verify.groovy
  src/it/projects/tree-multimodule/module-a/expected-v4.txt
  src/it/projects/tree-multimodule/module-b/expected-v4.txt
  src/it/projects/tree-multimodule/test.properties
  src/it/projects/tree-multimodule/verify.groovy
  src/it/projects/tree-scope/expected1-v4.txt
  src/it/projects/tree-scope/expected2-v4.txt
  src/it/projects/tree-scope/invoker.properties
  src/it/projects/tree-scope/test1.properties
  src/it/projects/tree-scope/test2.properties
  src/it/projects/tree-scope/verify.groovy
  src/it/projects/tree-verbose-multimodule/module-a/expected-v4.txt
  src/it/projects/tree-verbose-multimodule/module-b/expected-v4.txt
  src/it/projects/tree-verbose-multimodule/test.properties
  src/it/projects/tree-verbose-multimodule/verify.groovy
  src/it/projects/tree-verbose/expected-v4.txt
  src/it/projects/tree-verbose/test.properties
  src/it/projects/tree-verbose/verify.groovy
  src/it/projects/tree/expected-v4.txt
  src/it/projects/tree/test.properties
  src/it/projects/tree/verify.groovy
  src/main/java/org/apache/maven/plugins/dependency/ListRepositoriesMojo.java
Labels: build

#1490 Clean up AbstractDependencyMojoTestCase setUp
  src/test/java/org/apache/maven/plugins/dependency/AbstractDependencyMojoTestCase.java
  src/test/java/org/apache/maven/plugins/dependency/TestCollectMojo.java
  src/test/java/org/apache/maven/plugins/dependency/TestGetMojo.java
  src/test/java/org/apache/maven/plugins/dependency/TestListClassesMojo.java
  src/test/java/org/apache/maven/plugins/dependency/TestPropertiesMojo.java
  src/test/java/org/apache/maven/plugins/dependency/exclusion/AnalyzeExclusionsMojoTest.java
  src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestArtifactItem.java
  src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestCopyMojo.java
  src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestIncludeExcludeUnpackMojo.java
  src/test/java/org/apache/maven/plugins/dependency/fromConfiguration/TestUnpackMojo.java
  src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestBuildClasspathMojo.java
  src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo.java
  src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestCopyDependenciesMojo2.java
  src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestIncludeExcludeUnpackDependenciesMojo.java
  src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo.java
  src/test/java/org/apache/maven/plugins/dependency/fromDependencies/TestUnpackDependenciesMojo2.java
  src/test/java/org/apache/maven/plugins/dependency/resolvers/GoOfflineMojoTest.java
  src/test/java/org/apache/maven/plugins/dependency/resolvers/ResolveDependenciesMojoTest.java
  src/test/java/org/apache/maven/plugins/dependency/resolvers/TestResolveMojo.java
  src/test/java/org/apache/maven/plugins/dependency/tree/TestTreeMojo.java
  src/test/java/org/apache/maven/plugins/dependency/utils/TestDependencyStatusSets.java
  src/test/java/org/apache/maven/plugins/dependency/utils/translators/TestClassifierTypeTranslator.java
Labels: skip-changelog

#1508 Update site descriptor to 2.0.0
  src/site/site.xml
Labels: maintenance
